#!/bin/bash

export HOME=/app

unset GEM_PATH
if [ -d .profile.d ]; then
        for i in .profile.d/*.sh; do
                if [ -r $i ]; then
                        . $i
                fi
        done
        unset i
fi

DROPLET_BASE_DIR=$PWD
echo $$ >> $DROPLET_BASE_DIR/run.pid
exec bash -c "$*"
